---
version: "3.9"
services:
  dayz:
    image: "sludgerick/dayzexp"
    restart: always
    build:
      context: .
      args:
        - STEAMUSERNAME=$STEAMUSERNAME
        - STEAMPASSWORD=$STEAMPASSWORD
        - PROFILEDIR=$PROFILEDIR
        - PORT=$PORT
        - TIMEZONE=$TIMEZONE

    entrypoint: ./entry.sh
    env_file: .env
    ports:
#       - "2302:2302"
#       - "2303:2303/udp"
#       - "2304:2304/udp"
#       - "27016:27016"
#       - "36533:36533/tcp"
        - "2302-2304:2302-2304/udp"
        - "2302:2302/tcp"
        - "27015-27030:27015-27030/tcp"
        - "27036-27037:27036-27037/tcp"
        - "27000-27031:27000-27031/udp"
        - "36533:36533/tcp"
    # environment:
    volumes:
      - ./storage:/root/dayzserver-exp/mpmissions/dayzOffline.chernarusplus/storage_1/
      - ./ban.txt:/root/dayzserver-exp/ban.txt:rw
      - ./priority.txt:/root/dayzserver-exp/priority.txt:rw
      - ./whitelist.txt:/root/dayzserver-exp/whitelist.txt:rw
      - ./profile1:/root/profile1:rw
      - ./logs:/root/.local/share/DayZ Exp/
      # - ./core:/root/dayzserver-exp/core:ro
      # - ./serverfiles:/root/dayzserver-exp

#
#volumes:
#  serverfiles:
#  profile1:
